# Generated by Django 3.2.4 on 2021-07-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
